siteUid: null
sortOrder: 3
template: /form/bootstrap/edit_submission
uriParts:
  - form/bootstrap/
  -
    - slug
    - '[^\/]+'
  - /submissions/edit/
  -
    - token
    - \w+
uriPattern: 'form/bootstrap/<slug:[^\/]+>/submissions/edit/<token:\w+>'
