field: b494bf2c-eafd-4194-99a9-559a9549d81e
fieldLayouts:
  76bba208-2219-45e2-aabb-4bfb95451840:
    tabs:
      -
        fields:
          370c1b69-2c83-419f-aeed-4a6ab33242cb:
            required: true
            sortOrder: 2
          a31e6f46-afaf-4af7-ad33-c1ac0ebf6f9d:
            required: true
            sortOrder: 3
          acf70de9-f8a7-4f8c-8882-e4a89cb6cc62:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  370c1b69-2c83-419f-aeed-4a6ab33242cb:
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: ''
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a31e6f46-afaf-4af7-ad33-c1ac0ebf6f9d:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: 'Image position'
    searchable: true
    settings:
      default: right
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - ''
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  acf70de9-f8a7-4f8c-8882-e4a89cb6cc62:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textImage
name: 'Text & Image'
sortOrder: 4
