fieldLayouts:
  81a11fca-faee-42c3-b862-7ccac3831ea2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: videos
hasUrls: true
name: 'Video''s'
settings:
  path: '@basePath/storage/assets/videos'
sortOrder: 3
type: craft\volumes\Local
url: '@baseUrl/assets/videos'
