contentColumnType: text
fieldGroup: 7c4e2735-1749-4be8-bf8f-ea4263b6938b
handle: backgroundColor
instructions: ''
name: Achtergrondkleur
searchable: false
settings:
  options: ''
  palette: ''
  useConfigFile: '1'
translationKeyFormat: null
translationMethod: site
type: percipioglobal\colourswatches\fields\ColourSwatches
