contentColumnType: string
fieldGroup: a5394e36-c5da-4690-813f-bbb839bdbb0e
handle: builder
instructions: ''
name: Builder
searchable: true
settings:
  maxBlocks: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
