contentColumnType: string
fieldGroup: ec17aa49-c101-4f11-b7cd-e36919065cbe
handle: headerAsset
instructions: ''
name: 'Header Asset'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  defaultUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
