contentColumnType: boolean
fieldGroup: 7c4e2735-1749-4be8-bf8f-ea4263b6938b
handle: imgSize
instructions: ''
name: 'Afbeelding grootte'
searchable: false
settings:
  default: false
  offLabel: 'Volledige grootte'
  onLabel: Ingezoomd
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
