contentColumnType: string
fieldGroup: 00f652d6-c8ce-4f88-9b78-fb606319e79c
handle: logo
instructions: ''
name: Logo
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds: null
  defaultUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: ''
  restrictFiles: ''
  selectionLabel: 'Voeg je logo toe'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
