contentColumnType: string
fieldGroup: 7c4e2735-1749-4be8-bf8f-ea4263b6938b
handle: position
instructions: ''
name: Positie
searchable: false
settings:
  default: left
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - ''
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: site
type: rias\positionfieldtype\fields\Position
