contentColumnType: string
fieldGroup: 3e8e6e1e-d8a8-4001-9310-ddd73a81cb80
handle: teaserImage
instructions: ''
name: 'Teaser Afbeelding'
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:56927c8a-e051-4381-aa6c-4100a9fa4991'
  targetSiteId: null
  useSingleFolder: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
