dateModified: 1620719466
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER
  replyToEmail: $REPLY_EMAIL
  template: null
  transportSettings:
    encryptionMethod: tls
    host: $MAIL_HOST
    password: $MAIL_PASSWORD
    port: $MAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $MAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
    settings:
      customCss: ''
      customLinks:
        -
          __assoc__:
            -
              - linkLabel
              - 'Globale instellingen'
            -
              - linkUrl
              - /admin/globals
            -
              - adminOnly
              - ''
      displayDashboardLink: true
      displayDefaultEditSection: true
      displayEditAuthor: true
      displayEditDate: true
      displayGreeting: true
      displayGuideLink: true
      displayLogout: true
      displayRevisionNote: true
      displaySettingsLink: true
      enableMobileMenu: true
      widgets:
        __assoc__:
          -
            - admin-bar_edit-links
            - '1'
  breadcrumb:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.1.1
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fingerprint-assets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: 5W66A7U3YAL47SJL8ISFW30V
    schemaVersion: 3.3.1
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: ''
      autoScrollToErrors: '1'
      badgeType: all
      blockedEmails: ''
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: ''
      blockedKeywords: ''
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: ''
      customErrorMessage: ''
      customHoneypotName: ''
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: ''
      displayFeed: false
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: ''
      footerScripts: false
      formSubmitDisable: '1'
      formSubmitExpiration: ''
      formTemplateDirectory: null
      formattingTemplate: tailwind.html
      freeformHoneypot: '1'
      freeformHoneypotEnhancement: ''
      hideBannerDemo: '1'
      hideBannerOldFreeform: false
      minimumSubmitTime: ''
      pluginName: ''
      purgableSpamAgeInDays: '0'
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      removeNewlines: ''
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: ''
      showErrorsForBlockedKeywords: ''
      showTutorial: false
      spamFolderEnabled: ''
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: ''
      submissionThrottlingTimeFrame: m
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: '1'
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 9CSDTRPVDY56W8RZQVZRF28R
    schemaVersion: 1.0.21
  neo:
    edition: standard
    enabled: true
    licenseKey: KLF3CMAXSAC9QVZ71V3FHRH7
    schemaVersion: 2.8.16
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-anchors:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  section-field:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Template'
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
