fieldLayouts:
  bc24330b-7e09-4e95-9069-380eca5aeaa6:
    tabs:
      -
        fields:
          ca966992-20b9-48cf-bb88-821dd048f877:
            required: false
            sortOrder: 1
        name: Global
        sortOrder: 1
handle: globals
name: Algemeen
